<!--
 *
 * FaZend Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt. It is also available 
 * through the world-wide-web at this URL: http://www.fazend.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@fazend.com so we can send you a copy immediately.
 *
-->

<?php $this->headTitle("Internal error") ?>

<h1>Temporary internal site error</h1> 

<p>Error code: <?php echo  $this->message ?></p> 

<?php if ($this->showError): ?> 

    <p>Exception information (<?php echo get_class($this->exception)?>):</p> 

    <p>Error: <?php echo $this->exception->getMessage() ?></p> 

    <p>Stack:</p> 

    <pre><?php echo $this->exception->getTraceAsString() ?></pre> 

    <p>Request:</p> 

    <pre><?php var_dump($this->request->getParams()) ?></pre> 

<?php else: ?>

    <p style="width: 800px;">
        There is an internal error in the site. Our administrator already received
        a notification by email. However, if you want to get in touch with us 
        immediately you can email us. Thanks for your patience.
    </p>

<?php endif;
