<?php if ($this->pageCount > 1): ?>
	<div class="paginationControl">
	
	<!-- Previous page link -->
	<?php if (isset($this->previous)): ?>
		<a href="<?= $this->url(array('page'=>$this->previous));?>">prev</a> 
	<?php else: ?>
		<span style="color: grey;">prev</span>
	<?php endif; ?>

	&#32;

	<!-- Numbered page links -->
	<?php foreach ($this->pagesInRange as $page): ?>
		<?php if ($page != $this->current): ?>
			<a href="<?=$this->url(array('page'=>$page));?>"><?=$page;?></a>
		<?php else: ?>
			[<?= $page; ?>]
		<?php endif; ?>
		&#32;
	<?php endforeach; ?>

	&#32;

	<!-- Next page link -->
	<?php if (isset($this->next)): ?>
		<a href="<?= $this->url(array('page'=>$this->next));?>">next</a>
	<?php else: ?>
		<span style="color: grey;">next</span>
	<?php endif; ?>
	</div>
<?php endif; ?>