<!--
 *
 * FaZend Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt. It is also available
 * through the world-wide-web at this URL: http://www.fazend.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@fazend.com so we can send you a copy immediately.
 *
-->

<?php if ($this->pageCount > 1): ?>
    <div class="paginationControl">

    <!-- Previous page link -->
    <?php if (isset($this->previous)): ?>
        <a href="<?php echo  $this->url(array('page'=>$this->previous));?>">prev</a>
    <?php else: ?>
        <span style="color: grey;">prev</span>
    <?php
endif; ?>

    &#32;

    <!-- Numbered page links -->
    <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
            <a href="<?php echo $this->url(array('page'=>$page));?>"><?php echo $page;?></a>
        <?php else: ?>
            [<?php echo  $page; ?>]
        <?php
endif; ?>
        &#32;
    <?php
endforeach; ?>

    &#32;

    <!-- Next page link -->
    <?php if (isset($this->next)): ?>
        <a href="<?php echo  $this->url(array('page'=>$this->next));?>">next</a>
    <?php else: ?>
        <span style="color: grey;">next</span>
    <?php
endif; ?>
    </div>
<?php
endif;
