<!--
 *
 * FaZend Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt. It is also available 
 * through the world-wide-web at this URL: http://www.fazend.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@fazend.com so we can send you a copy immediately.
 *
-->

<? $this->headTitle('adm: ' . $this->action) ?>

<p>
    <? foreach(scandir(FAZEND_PATH . '/View/scripts/adm') as $file): ?>

        <? if (($file == 'index.phtml') || ($file[0] == '_')) continue; ?>
        
        <? $matches = array(); if (!preg_match('/^(.*)\.phtml$/', $file, $matches)) continue; ?>
        
        <? if (isset($notFirst)): ?>
            |
        <? else: ?>
            <? $notFirst = true ?>
        <? endif; ?>

        <?=($matches[1] == $this->action ? '[' : false)?><a href="<?=$this->url(array('action'=>$matches[1]), 'adm', true)?>"><?=$matches[1]?></a><?=($matches[1] == $this->action ? ']' : false)?>

    <? endforeach; ?>
</p>    
