<!--
 *
 * FaZend Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt. It is also available 
 * through the world-wide-web at this URL: http://www.fazend.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@fazend.com so we can send you a copy immediately.
 *
-->

<?php $this->headTitle('adm: ' . $this->action) ?>

<p>
    <?php foreach(scandir(FAZEND_PATH . '/View/scripts/adm') as $file): ?>

        <?php if (($file == 'index.phtml') || ($file[0] == '_')) continue; ?>
        
        <?php $matches = array(); if (!preg_match('/^(.*)\.phtml$/', $file, $matches)) continue; ?>
        
        <?php if (isset($notFirst)): ?>
            |
        <?php else: ?>
            <?php $notFirst = true ?>
        <?php endif; ?>

        <?php echo ($matches[1] == $this->action ? '[' : false)
            ?><a href="<?php echo $this->url(array('action'=>$matches[1]), 'adm', true)?>"
                ><?php echo $matches[1]?></a><?php echo ($matches[1] == $this->action ? ']' : false)?>

    <?php endforeach; ?>
</p>    
