<!--
 *
 * FaZend Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt. It is also available 
 * through the world-wide-web at this URL: http://www.fazend.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@fazend.com so we can send you a copy immediately.
 *
-->

<?=$this->render('adm/_menu.phtml')?>

<h1>Backup</h1>

<p>Latest backup done: <tt><?=date('m/d/y h:i:s', $this->backup->getLatestRunTime())?></tt> 
    (<a href="<?=$this->url(array('clear'=>true))?>">clear semaphore</a>)</p>

<pre><?=$this->backup->getLatestLog()?></pre>

<p>All objects in your S3 bucket:</p>

<ul>
<? foreach ($this->files as $file): ?>
    <li><?=$file['name']?>: <?=$file['size']?> bytes, <?=date('m/d/y h:i', $file['mtime'])?></li>
<? endforeach; ?>
</ul>

