<!--
 *
 * FaZend Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt. It is also available 
 * through the world-wide-web at this URL: http://www.fazend.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@fazend.com so we can send you a copy immediately.
 *
-->

<?=$this->render('adm/_menu.phtml')?>

<h1>error_log on server</h1>

<p>Location: <tt><?=$this->filePath?></tt> (<?=file_exists($this->filePath) ? filesize($this->filePath) . 'bytes' : 'no file'?>, 
    <a href="<?=$this->url(array('clear'=>true))?>">clear log</a>)</p>

<pre><?=$this->log?></pre>
