<!--
 *
 * FaZend Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt. It is also available 
 * through the world-wide-web at this URL: http://www.fazend.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@fazend.com so we can send you a copy immediately.
 *
-->

<? if ($this->node): ?>

    <?=$this->partial('adm/pos/versions.phtml', array('node'=>$this->node))?>

<? else: ?>

    <ul style="line-height: 1.3em;">
    <?=$this->partial('adm/pos/node.phtml', array(
        'node' => FaZend_Pos_Abstract::root(), 
        'label' => 'root'))?>
    </ul>
    
<? endif; ?>