<?=$this->render('adm/_menu.phtml')?>

<h1>SqueezePNG files</h1>

<p>
	Holder: <tt><?=$this->squeezePNG()->getImagePath()?></tt><br/>
	Map file: <tt><?=$this->squeezePNG()->getMapPath()?></tt>
</p>	

<img src="<?=$this->squeezePNG()->url()?>" style="padding: 5px; border: 1px solid gray;"/>

<? $map = $this->squeezePNG()->loadMap()?>

<p>Squeezed images in the holder (<a href="<?=$this->url(array('reload'=>true))?>">reload</a>):</p>

<ul>
<? foreach ($map['images'] as $id=>$img): ?>

	<li>
		<?=basename($id)?>: <?=$img['width']?>x<?=$img['height']?>
	</li>	

<? endforeach; ?>
</ul>

