<!--
 *
 *
 *
 -->

<?
    $this->headMeta()
    	->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');
    	
    $this->headTitle('FaZend Framework Test Application');

    $this->stripCSS('global.css');
    
    $this->includeCSS('fazend.css');

?><?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>  
    <?=$this->headTitle()?>
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
    <?=$this->headStyle()?>
</head> 
<body>

    <div class="logo">

        <a href='<?=$this->url(array('controller'=>'index', 'action'=>'index'), 'default', true)?>'
            class="logo"
            style="<?=$this->squeezePNG('logo.png')?>"></a><br/>

        <?=$this->action('login', 'user')?>

    </div>
    
    <div class="wrapper">

        <?=$this->flashMessage()?>

        <?=$this->layout()->content?>

    </div>

    <?=$this->googleAnalytics()?>
    <?=$this->headScript() ?>
</body>
</html>
