<!--
 *
 * FaZend Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt. It is also available 
 * through the world-wide-web at this URL: http://www.fazend.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@fazend.com so we can send you a copy immediately.
 *
-->

<?php
    $this->headMeta()
        ->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');
        
    $this->headTitle('FaZend Framework Test Application');

    $this->stripCSS('global.css');
    
    $this->includeCSS('fazend.css');

?><?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>  
    <?php echo $this->headTitle()?>
    <?php echo $this->headMeta()?>
    <?php echo $this->headLink()?>
    <?php echo $this->headStyle()?>
</head> 
<body>

    <div class="logo">

        <a href='<?php echo $this->url(array('controller'=>'index', 'action'=>'index'), 'default', true)?>'
            class="logo"
            style="<?php echo $this->squeezePNG('logo.png')?>"></a><br/>

        <?php echo $this->action('login', 'user')?>

    </div>
    
    <div class="wrapper">

        <?php echo $this->flashMessage()?>

        <?php echo $this->layout()->content?>

    </div>

    <?php echo $this->googleAnalytics()?>
    <?php echo $this->headScript() ?>
</body>
</html>
