<?
$this->doctype('XHTML1_STRICT');

$this->headMeta()
	->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');

$this->stripCSS('global.css');

?><?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>  
<?=$this->headTitle()?>
<?=$this->headMeta()?>
<?=$this->headLink()?>
<?=$this->headStyle()?>
</head> 
<body>

<div style='width: auto; padding: 30px;'>

<a href='<?=$this->url(array('controller'=>'index', 'action'=>'index'), 'default', true)?>' 
	style="border: 0; <?=$this->squeezePNG('logo.png')?>"></a>

<?=$this->action('login', 'user', 'fazend')?>

<?=$this->layout()->content?>

</div>

<?=$this->googleAnalytics()?>
</body>
<?=$this->headScript() ?>
</html>