<!--
 *
 * FaZend Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt. It is also available 
 * through the world-wide-web at this URL: http://www.fazend.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@fazend.com so we can send you a copy immediately.
 *
-->

<li>
<b><?=$this->label?></b> 
    <a href="<?=$this->url(array(
        'action'=>'pos', 
        'object'=>$this->node->ps()->id), 'adm', true)?>">v<?=$this->node->ps()->version?></a>: 
    <?=$this->node->ps()->type?>

<ul>
<? foreach ($this->node->ps()->properties as $name): ?>
    <? if (substr($name, 0, strlen(FaZend_Pos_Properties::ARRAY_PREFIX)) == FaZend_Pos_Properties::ARRAY_PREFIX): ?>
        <? $label = '[' . substr($name, strlen(FaZend_Pos_Properties::ARRAY_PREFIX)) . ']' ?>
    <? else: ?>
        <? $label = $name ?>
    <? endif; ?>
    <? if ($this->node->$name instanceof FaZend_Pos_Abstract): ?>
        <?=$this->partial('adm/pos/node.phtml', array(
            'node' => $this->node->$name,
            'label' => $label))?>    
    <? elseif (is_scalar($this->node->$name)): ?>
        <li><?=$label?>: <?=$this->node->$name?></li>
    <? else: ?>
        <li><?=$label?>: <?=get_class($this->node->$name)?></li>
    <? endif; ?>
<? endforeach; ?>
</ul>

</li>