<li>
<b><?=$this->label?></b> 
    <span style="color:gray;">v<?=$this->node->ps()->version?></span>: 
    <?=$this->node->ps()->type?>

<ul>
<? foreach ($this->node->ps()->properties as $name): ?>
    <? if (substr($name, 0, strlen(FaZend_Pos_Properties::ARRAY_PREFIX)) == FaZend_Pos_Properties::ARRAY_PREFIX): ?>
        <? $label = '[' . substr($name, strlen(FaZend_Pos_Properties::ARRAY_PREFIX)) . ']' ?>
    <? else: ?>
        <? $label = $name ?>
    <? endif; ?>
    <? if ($this->node->$name instanceof FaZend_Pos_Abstract): ?>
        <?=$this->partial('adm/pos/node.phtml', array(
            'node' => $this->node->$name,
            'label' => $label))?>    
    <? elseif (is_scalar($this->node->$name)): ?>
        <li><?=$label?>: <?=$this->node->$name?></li>
    <? else: ?>
        <li><?=$label?>: <?=get_class($this->node->$name)?></li>
    <? endif; ?>
<? endforeach; ?>
</ul>

</li>