<?='<?xml version="1.0" encoding="utf-8" ?>'?>
<?='<?xml-stylesheet'?> type="text/css" href="<?=$this->url(array('css'=>'uml.css'), 'css', true, false)?>" <?='?>'?> 
<svg xmlns="http://www.w3.org/2000/svg" 
    version="1.1" 
    xmlns:xlink="<?=FaZend_Pan_Analysis_Component_Abstract::XLINK_NS?>"
    width="<?=FaZend_Pan_Analysis_Diagram::WIDTH?>px"
    height="<?=FaZend_Pan_Analysis_Diagram::HEIGHT?>px"
    viewBox="0 0 100 100">
    
<?=$this->svg?>
        
</svg>
