
<? if (!FaZend_User::isLoggedIn()): ?>

	<a href="#_self" onclick="document.getElementById('lf').style.display = 'block'; document.getElementById('lf').loginEmail.focus(); return false;">login</a> |

        <a href="<?=$this->url(array('action'=>'register'), 'user', true)?>">create account</a>

	<div id="lf"<?=(($this->form->email->hasValue() || $this->form->pwd->hasValue()) ? false : ' style="display: none;"')?>><?=$this->form?></div>

<? else: ?>

	<?=$this->escape(FaZend_User::getCurrentUser()->email)?><br/>

	<a href="<?=$this->url(array('controller'=>'index', 'action'=>'settings'), 'default', true)?>">settings</a> | 
       	<a href="<?=$this->url(array('action'=>'logout'), 'user', true)?>">logout</a>

<? endif; ?>
