<!--
 *
 * FaZend Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt. It is also available 
 * through the world-wide-web at this URL: http://www.fazend.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@fazend.com so we can send you a copy immediately.
 *
-->

<?
$this->headMeta()
    ->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');

$this->includeCSS('fazend.css');

?><?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>  
    <?=$this->headTitle()?>
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
    <?=$this->headStyle()?>
</head> 
<body>

    <div class="hdr">
        <? if (APPLICATION_ENV !== 'production'): ?>
            <a href="<?=$this->url(array('action'=>'index', 'id'=>'index/index'), 'ui', true, false)?>">UI Modeller</a> &middot;
            <a href="<?=$this->url(array(), 'analysis', true, false)?>">Analysis Model</a> &middot;
            <a href="<?=$this->url(array('action'=>'index'), 'units', true, false)?>">Unit Tests</a> &middot;
            <a href="<?=$this->url(array(), 'dbmap', true, false)?>">DB Mapper</a> &middot;
        <? endif; ?>
        <a href="<?=$this->url(array(), 'adm', true, false)?>">Admin Area</a>

        <?=WEBSITE_URL?>
    </div>
    
    <div class="content">
        <?=$this->flashMessage()?>
        <?=$this->layout()->content?>
    </div>

    <div class="btm">
        (c) <?=FaZend_Properties::get()->name?>/Zend <?=Zend_Version::VERSION?>/FaZend <?=FaZend_Version::VERSION?>, 
        rev.<?=FaZend_Revision::get()?>, <?=$this->pageLoadTime()?>
    </div>

    <?=$this->headScript() ?>
</body>
</html>