<!--
 *
 * FaZend Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt. It is also available 
 * through the world-wide-web at this URL: http://www.fazend.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@fazend.com so we can send you a copy immediately.
 *
-->

<?php
$this->headMeta()
    ->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');

$this->includeCSS('fazend.css');

?><?php echo  $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>  
    <?php echo $this->headTitle()?>
    <?php echo $this->headMeta()?>
    <?php echo $this->headLink()?>
    <?php echo $this->headStyle()?>
</head> 
<body>

    <div class="hdr">
        <?php if (APPLICATION_ENV !== 'production'): ?>
            <a href="<?php echo $this->url(array('action'=>'index', 'id'=>'index/index'), 'ui', true, false)?>"
                >UI Modeller</a> &middot;
            <a href="<?php echo $this->url(array(), 'analysis', true, false)?>"
                >Analysis Model</a> &middot;
            <a href="<?php echo $this->url(array('action'=>'index'), 'units', true, false)?>"
                >Unit Tests</a> &middot;
            <a href="<?php echo $this->url(array(), 'dbmap', true, false)?>"
                >DB Mapper</a> &middot;
        <?php endif; ?>
        <a href="<?php echo $this->url(array(), 'adm', true, false)?>">Admin Area</a>

        <?php echo WEBSITE_URL?>
    </div>
    
    <div class="content">
        <?php echo $this->flashMessage()?>
        <?php echo $this->layout()->content?>
    </div>

    <div class="btm">
        (c) <?php echo FaZend_Properties::get()->name?>/Zend 
            <?php echo Zend_Version::VERSION?>/FaZend 
            <?php echo FaZend_Version::VERSION?>, 
        rev.<?php echo FaZend_Revision::get()?>, <?php echo $this->pageLoadTime()?>
    </div>

    <?php echo $this->headScript() ?>
</body>
</html>