<?
$this->headMeta()
    ->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');

$this->stripCSS('ui.css');

?><?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>  
<?=$this->headTitle()?>
<?=$this->headMeta()?>
<?=$this->headLink()?>
<?=$this->headStyle()?>
</head> 
<body>

<?=$this->layout()->content?>

<?=$this->headScript() ?>
</body>
</html>