<?

$this->headMeta()
    ->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');

$this->includeCSS('fazend.css');
$this->includeCSS('units.css');

$this->includeJQuery();
$this->includeJS('units.js');

$this->headTitle('units');

?><?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>  
    <?=$this->headTitle()?>
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
    <?=$this->headStyle()?>
</head> 
<body>

    <div class="wrapper">
        <?=$this->layout()->content?>
    </div>

    <?=$this->headScript() ?>
</body>
</html>