<!--
 * comments...
 -->
 
<p>This is forma:</p>

<?php echo $this->forma()
    ->addBehavior('showLog')
    ->addBehavior(
        'flash', 
        'sprintf("FLASH++ for %s (%d bytes in reason)", ${a1}, strlen(${a4}))'
    )
    ->addBehavior('redirect', 'submitted', 'index')
    ->addField('text', 'name')
        ->fieldLabel('Your full name')
        ->fieldAttrib('maxlength', 45)
    ->addField('select', 'client')
        ->fieldLabel('Are you our client?')
        ->fieldOptions(array(1=>'yes', 0=>'no'))
        ->fieldConverter('boolean')
    ->addField('hidden', 'address')
        ->fieldValue('some address')
    ->addField('textarea', 'reason')
        ->fieldAttrib('cols', 15)
        ->fieldLabel('Why are you interested in our services?')
    // ->addField('file')
    //     ->fieldRequired(true)
    //     ->fieldLabel('Signed NDA in PDF')
    ->addField('submit', 'submit')
        ->fieldValue('go')
        ->fieldAction(array('Model_Owner', 'register'))
    ?>
    
<p>test</p>