<!--
 * comments...
 * @see IndexController::mockupAction()
 -->
 
<!-- @actor("RegisteredUser") -->

<!-- @text("You can edit your photos...") -->
<!-- @text("Some useful meta-s: 
    %name%
    %company%
    %address%
    %country%
    %phone%
    %city%
    %zip%
    %currency%
    %fdate%
    %date%
    %pdate%
    %iban%
    %bank%
    %swift%
    
    %2d%% : 15%%
    %10s : some text...
    %f : floating point number in (0..1)
    %d : integer 13
    ") -->

<p>You can edit your photos:</p>

<!-- @table()
    ->addColumn("id", 'id', 'id')
    ->addColumn("description", 'id', 'id')
    ->addOption("disable", 'disable')
    ->addOption("enable", 'enable') 
    ->addLink('id', false)
    ->setPaginator()
    -->

<table>
    <tr><td><?php echo $this->line?></td></tr>
</table>

<!-- @link("Upload new photo", "photos/upload") -->

<a href="<?php echo $this->url(
    array('controller'=>'photos', 'action'=>'upload'), 
    'default', 
    true
)?>">upload new photo</a>

<!-- @form()
    ->addField("text", 'text', 'tt', "Title of your photo:")
    ->addField('area', 'textarea', '%500s', "Description") 
    ->addField('title', 'select', array('Mr', 'Mrs'), "Title") 
    ->addField('submit', 'submit', false, 'Save') 
    ->setAlignedStyle(false)
    -->

<?php echo $this->form?>

<p>test</p>