
<!-- @actor("RegisteredUser") -->

<!-- @text("You can edit your photos...") -->

<p>You can edit your photos:</p>

<!-- @table()
    ->addColumn("id", 'id', 'id')
    ->addColumn("description", 'id', 'id')
    ->addOption("disable", 'disable')
    ->addOption("enable", 'enable') -->

<table>
    <tr><td><?=$this->line?></td></tr>
</table>

<!-- @link("Upload new photo", "photos/upload") -->

<a href="<?=$this->url(array('controller'=>'photos', 'action'=>'upload'), 'default', true)?>">upload new photo</a>

<!-- @form()
    ->addField("text", 'text', 'tt', "Title of your photo:")
    ->addField("textarea", 'text', 'dd', "Description") -->

<?=$this->form?>