
<?
    $this->headTitle($this->script);
?>

<div class="wrapper">

    <div class="header">
        <div class="actor">
            <?=$this->actor?>
        </div>

        <div class="path">
            <?=$this->script?>
        </div>

        <div class="link">
            <a href="<?=$this->url(array('action'=>'mockup', 'id'=>$this->script), 'ui', true, false)?>">PNG</a>
        </div>
    </div>

    <div class="page">
        <div class="nav">
            <?=$this->navigation()->menu()
                ->setMaxDepth(2)
                ->setRenderParents(true)?>
        </div>

        <?=$this->page?>
    </div>

    <div class="logo">
        (c) FaZend.com
    </div>

</div>

