<!--
 *
 * FaZend Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt. It is also available 
 * through the world-wide-web at this URL: http://www.fazend.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@fazend.com so we can send you a copy immediately.
 *
-->

<?php
    $this->headTitle($this->script);
    $this->includeCSS('ui.css');
?>

<div class="wrapper">

    <div class="header">
        <div class="actor">
            <?php echo $this->actor?>
        </div>

        <div class="path">
            <?php echo $this->script?>
        </div>

        <div class="link">
            <a href="<?php echo $this->url(array('action'=>'mockup', 'id'=>$this->script), 'ui', true, false)?>" 
                title="View this mock-up as image (PNG)">PNG</a>
        </div>
    </div>

    <div class="page">
        
        <div class="nav">
            <?php echo $this->navigation()->menu()
                ->setMaxDepth(2)
                ->setRenderParents(true)?>
        </div>

        <div class="actors">
            <?php echo $this->actors?>
        </div>

        <?php echo $this->page?>
    </div>

</div>

